<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="KUBNEEZ" failures="1" tests="6" name="Personal Loan" time="0.072" errors="0" timestamp="2023-12-29T17:01:26 IST">
  <testcase classname="test.day1" name="Demo" time="0.008"/>
  <testcase classname="test.day2" name="payloan" time="0.002"/>
  <testcase classname="test.day3" name="MobileloginHomeloan" time="0.002"/>
  <testcase classname="test.day3" name="WebloginHomeloan" time="0.002"/>
  <testcase classname="test.day3" name="loginAPIHomeloan" time="0.001"/>
  <testcase classname="test.day5" name="failDemo" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day5.failDemo(day5.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- failDemo -->
  <testcase classname="test.day1" name="Demo1" time="0.0">
    <ignored/>
  </testcase> <!-- Demo1 -->
</testsuite> <!-- Personal Loan -->
